config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: :omniauth_callbacks, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  root to: "posts#index"
  devise_for :users, skip: :omniauth_callbacks, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :posts
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  resources :categories
  resources :comments
  namespace :profile do
    resources :users, only: [:index, :edit, :update]
    patch "update_role/:id", to: "users#update_role", as: "update_role"
  end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings, dependent: :destroy
  belongs_to :category
  belongs_to :user
  acts_as_commentable
  mount_uploader :preview, ImageUploader
  validates :title, presence: true, length: {maximum: 255}
  validates :summary, presence: true, length: {maximum: 255}
  validates :body, presence: true

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:tags, :category, :user).order(:created_at).reverse_order.paginate(page: params[:page], per_page: 5)
    authorize! :index, Post
  end

  def show
    @post = Post.includes(:tags, :category, :user).find(params[:id])
    @new_comment = Comment.build_from(@post, current_user.id, "") if user_signed_in?
    respond_to do |format|
      format.html
      format.pdf {render template: "posts/show", pdf: "show"}
    end
  end

  def new
    if params[:user_id]
      @user = User.find(params[:user_id])
      @post = @user.posts.build
    else
      @post = current_user.posts.build
    end
    authorize! :create, @post
  end

  def create
    @user = User.find(post_params[:user_id])
    @post = @user.posts.build(post_params)
    authorize! :create, @post
    if @post.save
      redirect_to @post, success:  "#{t(".success_create")}"
    else
      render :new
    end
  end

  def edit
    unless @post = Post.find_by_id(params[:id])
      @post = Post.new
    end
    authorize! :update, @post
  end

  def update
    @post = Post.find_by_id(params[:id])
    authorize! :update, @post
    if @post
      @post.update(post_params)
      redirect_to @post , success:  "#{t(".success_update")}"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    if @post.destroy
      redirect_to posts_path, success:  "#{t(".success_destroy")}"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :summary, :body, :all_tags, :category_id, :user_id, :preview)
  end


end

app/helpers/posts_helper.rb
module PostsHelper


  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end

  end
end

app/views/posts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <h5><%= t("common.errors") %></h5>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= render "errors", object: @post %>

<%= form_for @post, :html => { :multipart => true } do |f| %>
  <%= f.hidden_field :user_id, value: @post.user_id %>
  <div class = "form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :preview %>
    <%= f.file_field :preview %>
  </div>

  <div class = "form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: "editor" %>
  </div>

  <div class="form-group">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, {include_blank: true},  class: "form-control" %>
  </div>

  <div class="form-group">
  <%= submit_tag t(".submit", action: t(submit_name(@post))), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <section class="post-head">
  <h3><%= link_to post.title, post_path(post) %></h3>
    <small>
    <time><%= post.created_at.strftime("%d.%m.%Y %H:%M") %></time> |
      <%= link_to post.user.name, edit_profile_user_path(post.user_id) if User.find_by_id(post.user_id)%> |
      <%= link_to post.category.name, post.category if post.category.present? %> |
      <% if can? :update, post %>
      <%= link_to t(".edit"), edit_post_path(post) %> |
      <%= link_to t(".delete"), post_path(post), method: :delete, data: { confirm: t(".confirm") } %>
        <% end %>
    </small>

  </section>
  <section class="post-summary">
    <p class="preview"><%= image_tag post.preview.url(:large) if post.preview.present? %></>
    <p><%= post.summary %></p>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: "badge badge-primary"}.join(" ") %>
  </section>

</div>

app/views/posts/edit.html.erb
<div class="title">
  <h1> <%= t(".title") %></h1>
</div>

<%= render "form" %>

app/views/posts/index.html.erb
<div class="title">
<h1><%= t(".title") %></h1>
</div>
<section id="posts">
<%= render @posts %>
</section>
<%=  will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/index.js.erb
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
$('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
$('.pagination').remove();
<% end %>

app/views/posts/show.html.erb
<div class="post">
  <section class="post-head">
    <h3><%=  @post.title %></h3>
    <small>
      <time><%= @post.created_at.strftime("%d.%m.%Y %H:%M") %></time> |
      <%= link_to @post.user.name, edit_profile_user_path(@post.user_id) if @post.user_id%> |
      <%= link_to @post.category.name, @post.category if @post.category.present? %> |
      <%= link_to "PDF", post_path(@post, format: "pdf") %>
      <% if can? :update, @post %>
      <%= link_to t(".edit"), edit_post_path(@post) %> |
      <%= link_to t(".delete"), post_path(@post), method: :delete, data: { confirm: t(".confirm") } %>
        <% end %>
    </small>

  </section>
  <section class="post-body">
    <p><%= @post.body.html_safe %></p>
  </section>

  <section class="footer-summary">
    <%= raw @post.tags.map(&:name).map {|t| link_to t, tag_path(t), class: "badge badge-primary"}.join(" ") %>
  </section>

  <section class="comment">
    <%= render partial: "comments/template", locals: {commentable: @post, new_comment: @comment} %>
  </section>

</div>

app/views/posts/show.pdf.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
<h1><%=@post.title%></h1>
<p><%=@post.summary%></p>
<p><%=@post.body.html_safe%></p>
</body>
</html>