config/routes.rb
Rails.application.routes.draw do

  devise_for :users, only: :omniauth_callbacks, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  root to: "posts#index"
  devise_for :users, skip: :omniauth_callbacks, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :posts
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  resources :categories
  resources :comments
  namespace :profile do
    resources :users, only: [:index, :edit, :update]
    patch "update_role/:id", to: "users#update_role", as: "update_role"
  end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newspaper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to t(".title"), root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to t(".authors"), profile_users_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav pull-xs-right">
          <% unless user_signed_in? %>
          <li class="nav-item">
            <%= link_to t(".sign_in"), user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(".sign_up"), new_user_registration_path, class: "nav-link" %>
          </li>
            <% else %>
            <% if can? :create , Post %>
            <li class="nav-item">
              <%= link_to t(".add_news"), new_post_path, class: "btn btn-outline-primary" %>
            </li>
              <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to t(".profile"), edit_profile_user_path(current_user.id), class: "dropdown-item" %>
                <% if can? :index, Category %>
                <%= link_to t(".categories"), categories_path, class: "dropdown-item" %>
                  <%end %>
                <div class="dropdown-divider"></div>
                <%= link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            <li class="nav-item">

            </li>
          <%end %>
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>
  </div>
<div class="container main">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, massage| %>
        <div class="alert <%= bootstrap_class_for(name) %>">
        <button class="close" data-dismiss="alert">&times;</button>
        <%= massage %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <%= yield %>
    </div>


    <div class="col-md-3">
      <%= render "shared/submenu" %>

      <div class="tag_cloud">
      <h2><%= t(".tags_cloud") %></h2>
      <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_calss| %>
      <%= link_to tag.name, tag_path(tag.name),class: css_calss %>
      <% end %>
    </div>
    </div>
  </div>
</div>

  </body>
</html>